version: '3.8'

services:
  web:
    build:
      context: .
      target: build  # Use the intermediate build stage with dev tools
      args:
        BUNDLE_WITHOUT: ""
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      BUNDLE_WITHOUT: production
    stdin_open: true
    tty: true

volumes:
  bundle:
